services:

  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    #environment:
    #  - APP_ENV=production
    #  - APP_DEBUG=false
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - .:/app
    networks:
      - app-network

  appstream:
    build:
      context: .
      dockerfile: ./stream/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - .:/appstream
    networks:
      - app-network

  redis:
    image: "redis"
    ports:
      - 6379
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge